enableGlobalCache: true

nodeLinker: node-modules
gitHooksPath: .github/hooks

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
      spec: "https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
