version: "3"
services:
    postgres1:
        image: postgres:latest
        container_name: postgres1
        networks: ["navia"]
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
networks:
    navia:
        driver: bridge
